// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBBNISXgISQ4zwz7RTpcCAemR6j-TXq6n0',
    appId: '1:829799319939:web:39eb83a1db1c91dacd0eb6',
    messagingSenderId: '829799319939',
    projectId: 'todolist-ef60f',
    authDomain: 'todolist-ef60f.firebaseapp.com',
    storageBucket: 'todolist-ef60f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDg0RGGUadyylaElO3sw1MyywuMEbLriEo',
    appId: '1:829799319939:android:708ab3a1eae9bde9cd0eb6',
    messagingSenderId: '829799319939',
    projectId: 'todolist-ef60f',
    storageBucket: 'todolist-ef60f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDD2HgEbuwkeNqWC22wwg1FpaCNitbJFAU',
    appId: '1:829799319939:ios:ff194711ef1d1d91cd0eb6',
    messagingSenderId: '829799319939',
    projectId: 'todolist-ef60f',
    storageBucket: 'todolist-ef60f.appspot.com',
    iosBundleId: 'com.example.appxcelAcademy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDD2HgEbuwkeNqWC22wwg1FpaCNitbJFAU',
    appId: '1:829799319939:ios:46d271a4d463f2eacd0eb6',
    messagingSenderId: '829799319939',
    projectId: 'todolist-ef60f',
    storageBucket: 'todolist-ef60f.appspot.com',
    iosBundleId: 'com.example.appxcelAcademy.RunnerTests',
  );
}
